import express from 'express';
import cors from 'cors';

const app = express();
const PORT = 5000;

app.use(cors());
app.use(express.json());

const records = [
  {
    id: 'fall-armyworm',
    name: 'Fall Armyworm',
    nameAr: 'دودة الجيش الخريفية',
    category: 'pest',
    scientificName: 'Spodoptera frugiperda',
    scientificNameAr: 'سبودوبتيرا فروجيبيردا',
    country: 'Global tropics and subtropics',
    iracGroup: '28-6',
    resistanceRisk: 'Medium',
    source: 'CABI • IRAC',
    summary: 'Highly polyphagous lepidopteran pest attacking maize, sorghum, rice and other cereals.',
    summaryAr: 'آفة حرشفية متعددة العوائل تهاجم الذرة والذرة الرفيعة والأرز والمحاصيل الحبوبية.',
    identification: 'Adults are grey-brown moths with a distinct pattern on the forewing; larvae have inverted Y on head and feed aggressively.',
    identificationAr: 'اليرقات ذات رأس على شكل Y مقلوب وتغذي على الأوراق بنشاط، بينما تكون الفراشات رمادية بنية.',
    damage: 'Leaf feeding, whorl damage, stem tunneling and severe defoliation in maize.',
    damageAr: 'تسبب تمزق الأوراق، وتلف القلب، ونفوق النبات في المراحل المبكرة.',
    lifeCycle: 'Lifecycle completed in 2–4 weeks under warm conditions, facilitating rapid population build-up.',
    lifeCycleAr: 'يكتمل دورة الحياة خلال 2–4 أسابيع في الظروف الدافئة، ما يسرّع تكاثرها.',
    control: 'Biological control, pheromone traps, cultural practices, and selective insecticides such as chlorantraniliprole.',
    controlAr: 'المكافحة الحيوية، المصائد الفيرمونية، الممارسات الزراعية، ومبيدات انتقائية مثل كلورانترانيليبرويل.',
    activeIngredients: ['Chlorantraniliprole', 'Emamectin benzoate', 'Spinetoram'],
    image: 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=900&q=80'
  },
  {
    id: 'fusarium-wilt',
    name: 'Fusarium Wilt',
    nameAr: 'ذبول الفيوزاريوم',
    category: 'disease',
    scientificName: 'Fusarium oxysporum',
    scientificNameAr: 'فيوزاريوم أوكسيسبورم',
    country: 'Global warm climates',
    iracGroup: 'NA',
    resistanceRisk: 'High',
    source: 'CABI • FAO',
    summary: 'Soil-borne fungal disease causing vascular wilting and plant collapse in many crops.',
    summaryAr: 'مرض فطري متوطن في التربة يسبب ذبولًا وعطلاً للنسج الوعائية في العديد من المحاصيل.',
    identification: 'Yellowing of lower leaves, wilting, browning of vascular tissue and plant death.',
    identificationAr: 'اصفرار الأوراق السفلية، ذبول، تلوّن الأوعية، ثم موت النبات.',
    damage: 'Severe yield loss as the pathogen blocks water transport in the xylem.',
    damageAr: 'يؤدي إلى خسارة محصولية كبيرة بسبب انسداد انتقال الماء.',
    lifeCycle: 'Survives in soil and plant debris for several years under favorable conditions.',
    lifeCycleAr: 'يستمر في التربة وبقايا النبات لعدة سنوات في الظروف المناسبة.',
    control: 'Crop rotation, resistant varieties, sanitation, soil health management and seed treatments.',
    controlAr: 'دوران المحصول، أصناف مقاومة، النظافة، إدارة صحة التربة ومعالجات البذور.',
    activeIngredients: ['Tebuconazole', 'Azoxystrobin'],
    image: 'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?auto=format&fit=crop&w=900&q=80'
  },
  {
    id: 'late-blight',
    name: 'Late Blight',
    nameAr: 'المرض المتأخر',
    category: 'disease',
    scientificName: 'Phytophthora infestans',
    scientificNameAr: 'فايتوفثورا إنفستانس',
    country: 'Temperate potato regions',
    iracGroup: 'NA',
    resistanceRisk: 'High',
    source: 'CABI • EPPO',
    summary: 'Devastating oomycete disease of potato and tomato, spreading rapidly under humid conditions.',
    summaryAr: 'مرض مدمّر في البطاطا والطماطم ينتشر بسرعة في الظروف الرطبة.',
    identification: 'Water-soaked lesions on foliage and stems, often with white sporulation on the underside of leaves.',
    identificationAr: 'آفات مبللة على الأوراق والساق، مع توبّع أبيض في الجانب السفلي.',
    damage: 'Can destroy leaves and tubers within days under conducive weather.',
    damageAr: 'يمكن أن يدمر الأوراق والدرنات خلال أيام في الطقس المناسب.',
    lifeCycle: 'Requires high humidity and cool temperatures, with rapid secondary spread.',
    lifeCycleAr: 'يتطلب رطوبة عالية ودرجات حرارة معتدلة مع انتشار ثانوي سريع.',
    control: 'Foliar fungicides, resistant varieties, reduced irrigation and prompt removal of diseased debris.',
    controlAr: 'مبيدات ورقية، أصناف مقاومة، تقليل الري، وإزالة بقايا النباتات المصابة فورًا.',
    activeIngredients: ['Mancozeb', 'Metalaxyl', 'Cymoxanil'],
    image: 'https://images.unsplash.com/photo-1518843875459-f738682238a6?auto=format&fit=crop&w=900&q=80'
  },
  {
    id: 'purple-nutsedge',
    name: 'Purple Nutsedge',
    nameAr: 'سعدان أرجواني',
    category: 'weed',
    scientificName: 'Cyperus rotundus',
    scientificNameAr: 'سايبرس روتوندس',
    country: 'Warm agroecosystems',
    iracGroup: 'HRAC: K3',
    resistanceRisk: 'High',
    source: 'CABI • HRAC',
    summary: 'Perennial sedge with high competitive ability and vegetative reproduction via tubers.',
    summaryAr: 'حشيشة معمرة تنافس بقوة وتتكاثر خضريًا عبر الدرنات.',
    identification: 'Triangular stems, glossy leaves, and purple-brown inflorescence with tuber production.',
    identificationAr: 'ساق مثلثة، أوراق لامعة، وبرعم أرجواني يخرج من الجذور.',
    damage: 'Reduces crop yield by competing strongly for water, nutrients, and light.',
    damageAr: 'تقلل الإنتاج بسبب منافسة قوية على الماء والمغذيات والضوء.',
    lifeCycle: 'Tubers allow survival through drought and repeated tillage cycles.',
    lifeCycleAr: 'تتحمل الجفاف والدورات الزراعية المتكررة عبر الدرنات.',
    control: 'Integrated management with herbicides, shallow cultivation and prevention of weed spread.',
    controlAr: 'إدارة متكاملة تشمل مبيدات، حراثة سطحية ومنع انتشار الحشائش.',
    activeIngredients: ['Glyphosate', 'Halosulfuron-methyl', 'S-metolachlor'],
    image: 'https://images.unsplash.com/photo-1471193945509-9ad0617afabf?auto=format&fit=crop&w=900&q=80'
  },
  {
    id: 'striga',
    name: 'Striga / Witchweed',
    nameAr: 'الستيجا / الحشيشة الساحرة',
    category: 'weed',
    scientificName: 'Striga hermonthica',
    scientificNameAr: 'ستيجا هيرمونثيكا',
    country: 'Sub-Saharan Africa',
    iracGroup: 'HRAC: C1',
    resistanceRisk: 'High',
    source: 'FAO • IITA',
    summary: 'Obligate parasitic weed that drains water and nutrients from cereal crops.',
    summaryAr: 'حشيشة طفيلية تجبر نفسها على التطفل على جذور الحبوب وتسحب الماء والمغذيات.',
    identification: 'Thin stems with pink-purple flowers emerging near host plants.',
    identificationAr: 'سيقان رفيعة وأزهار وردية أو بنفسجية تظهر قرب نباتات العائل.',
    damage: 'Severe yield loss, especially in maize and sorghum in low-input systems.',
    damageAr: 'تسبب خسائر كبيرة خصوصًا في الذرة والذرة الرفيعة في الأنظمة منخفضة المدخلات.',
    lifeCycle: 'Seeds remain viable in soil for many years and germinate in response to host root exudates.',
    lifeCycleAr: 'تبقى البذور صالحة في التربة لسنوات وتستجيب لمواد جذور العائل.',
    control: 'Resistant varieties, intercropping, seed bank reduction, and selective herbicides.',
    controlAr: 'أصناف مقاومة، تعددية المحاصيل، تقليل بنك البذور، ومبيدات انتقائية.',
    activeIngredients: ['Glyphosate', 'Imazapyr'],
    image: 'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?auto=format&fit=crop&w=900&q=80'
  },
  {
    id: 'barnyard-grass',
    name: 'Barnyard Grass',
    nameAr: 'حشيشة المزرعة',
    category: 'weed',
    scientificName: 'Echinochloa crus-galli',
    scientificNameAr: 'إتشينوشلويا كروس-غاللي',
    country: 'Global warm rice systems',
    iracGroup: 'HRAC: B',
    resistanceRisk: 'Medium',
    source: 'IRRI • CABI',
    summary: 'Aggressive annual grass that competes strongly with rice and other cereals.',
    summaryAr: 'نبات عشبي سنوي شديد التضخم وينافس الأرز والمحاصيل الحبوبية بقوة.',
    identification: 'Coarse upright stems with broad leaves and dense seed heads.',
    identificationAr: 'ساق منتصبة، أوراق واسعة، ونورات بذور كثيفة.',
    damage: 'Reduces stand, tillering and grain quality in wet systems.',
    damageAr: 'يخفض كثافة النبات وجودة الحبوب في الأنظمة المروية.',
    lifeCycle: 'Germinates rapidly after irrigation or rainfall and flowers quickly.',
    lifeCycleAr: 'ينبت بسرعة بعد الري أو المطر ويزهر بسرعة.',
    control: 'Pre-emergence and post-emergence herbicide programs and crop competition.',
    controlAr: 'برامج مبيدات قبل وبعد الإنبات، مع تنافس المحصول.',
    activeIngredients: ['Pendimethalin', 'Bensulfuron-methyl'],
    image: 'https://images.unsplash.com/photo-1471193945509-9ad0617afabf?auto=format&fit=crop&w=900&q=80'
  },
  {
    id: 'chlorantraniliprole',
    name: 'Chlorantraniliprole',
    nameAr: 'كلورانترانيليبرويل',
    category: 'ingredient',
    scientificName: 'Anthranilic diamide',
    scientificNameAr: 'ثنائي الأميد الأنثرايلي',
    country: 'Global use',
    iracGroup: '28',
    resistanceRisk: 'Moderate',
    source: 'IRAC • CABI',
    summary: 'Selective insecticide with powerful feeding cessation effects against lepidopteran pests.',
    summaryAr: 'مبيد حشري انتقائي يوقف التغذية في الآفات الحرشفية بشكل فعال.',
    identification: 'Systemic and translaminar activity with long residual control in crops.',
    identificationAr: 'نشاط نظامي وجانبي مع تأثير متبقٍ طويل في المحاصيل.',
    damage: 'Effective against yield-loss pests when larvae are feeding on foliage or fruits.',
    damageAr: 'فعّال ضد الآفات التي تسبّب خسائر في المحصول أثناء تغذية اليرقات.',
    lifeCycle: 'Not a biological lifecycle stage; instead it disrupts ryanodine receptors in insect muscles.',
    lifeCycleAr: 'ليس دورة حياة حيوية، بل يعيق مستقبلات ريانودين في عضلات الحشرة.',
    control: 'Used in integrated pest management programs to manage caterpillars and fruit worms.',
    controlAr: 'يُستخدم في الإدارة المتكاملة للآفات لمكافحة الدودة واليرقات الفاكهية.',
    activeIngredients: ['Chlorantraniliprole'],
    image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=900&q=80'
  },
  {
    id: 'azoxystrobin',
    name: 'Azoxystrobin',
    nameAr: 'أزوكسي ستروبين',
    category: 'ingredient',
    scientificName: 'Strobilurin fungicide',
    scientificNameAr: 'مبيد فطري من مجموعة ستروبيليورين',
    country: 'Global use',
    iracGroup: '11',
    resistanceRisk: 'Moderate',
    source: 'FRAC • CABI',
    summary: 'Broad-spectrum fungicide with protective and curative activity against many foliar diseases.',
    summaryAr: 'مبيد فطري واسع الطيف ذو فعالية وقائية وعلاجية.',
    identification: 'Interferes with mitochondrial respiration in fungal pathogens.',
    identificationAr: 'يعيق التنفس الخلوي في الفطريات المسببة للأمراض.',
    damage: 'Controls diseases including rusts, leaf spots and fruit rots.',
    damageAr: 'يُستخدم لمكافحة الصدأ، البقع الورقية، وتعفن الثمار.',
    lifeCycle: 'Used as a foliar treatment in several crop protection programs.',
    lifeCycleAr: 'يستخدم كمعالجة ورقية في العديد من برامج وقاية المحاصيل.',
    control: 'Apply preventively and in alternation with different modes of action to reduce resistance.',
    controlAr: 'يُطبق وقائيًا ويُستبدل بمبيدات ذات آليات مختلفة لتقليل المقاومة.',
    activeIngredients: ['Azoxystrobin'],
    image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=900&q=80'
  },
  {
    id: 'glyphosate',
    name: 'Glyphosate',
    nameAr: 'غليفوسات',
    category: 'ingredient',
    scientificName: 'EPSP synthase inhibitor',
    scientificNameAr: 'مثبط إنزيم EPSP سنتاز',
    country: 'Global use',
    iracGroup: 'G',
    resistanceRisk: 'High',
    source: 'HRAC • Weed Science',
    summary: 'Non-selective systemic herbicide widely used before planting or in glyphosate-tolerant crops.',
    summaryAr: 'مبيد أعشاب غير انتقائي ينتقل داخل النبات ويُستخدم قبل الزراعة أو في المحاصيل المتحملة.',
    identification: 'Blocks aromatic amino acid synthesis and causes chlorosis and death in susceptible weeds.',
    identificationAr: 'يمنع تصنيع الأحماض الأمينية العطرية، ما يؤدي إلى اصفرار النبات وموت الحشائش.',
    damage: 'Highly effective against annual and perennial broadleaf weeds and grasses.',
    damageAr: 'فعّال جدًا ضد الحشائش العريضة والخضر العشبية المعمرة.',
    lifeCycle: 'Translocated through the plant to growing points, killing both shoots and roots.',
    lifeCycleAr: 'ينتقل داخل النبات إلى نقاط النمو، مما يقتل السيقان والجذور.',
    control: 'Used in integrated weed management; rotation with other MOA groups is recommended.',
    controlAr: 'يُستخدم ضمن الإدارة المتكاملة للحشائش مع تدوير آليات مختلفة.',
    activeIngredients: ['Glyphosate'],
    image: 'https://images.unsplash.com/photo-1471193945509-9ad0617afabf?auto=format&fit=crop&w=900&q=80'
  },
  {
    id: 'maize',
    name: 'Maize',
    nameAr: 'الذرة',
    category: 'crop',
    scientificName: 'Zea mays',
    scientificNameAr: 'زيّا ميس',
    country: 'Global tropical and temperate zones',
    iracGroup: 'N/A',
    resistanceRisk: 'Low',
    source: 'FAO • CIMMYT',
    summary: 'Major cereal crop used for food, feed, starch and biofuel production.',
    summaryAr: 'محصول حبوب أساسي يُستخدم كغذاء وعلف ومواد نشوية ووقود حيوي.',
    identification: 'Tall plant with cobs and leaves arranged alternately on the stem.',
    identificationAr: 'نبات طويل مع سنابل وأوراق مرتبة بالتبادل على الساق.',
    damage: 'Affected by pests, drought, nutrient deficiency and weed competition.',
    damageAr: 'يتأثر بالآفات والجفاف ونقص العناصر ومنافسة الحشائش.',
    lifeCycle: 'Typically matures in 90–150 days depending on variety and climate.',
    lifeCycleAr: 'يكتمل نضجه خلال 90–150 يومًا بحسب الصنف والمناخ.',
    control: 'Balanced fertilization, irrigation scheduling, pest monitoring and weed management.',
    controlAr: 'التسميد المتوازن، جداول الري، رصد الآفات وإدارة الحشائش.',
    activeIngredients: ['Balanced nutrition', 'Irrigation management'],
    image: 'https://images.unsplash.com/photo-1532635241-0ebe6a2a8d18?auto=format&fit=crop&w=900&q=80'
  },
  {
    id: 'wheat',
    name: 'Wheat',
    nameAr: 'القمح',
    category: 'crop',
    scientificName: 'Triticum aestivum',
    scientificNameAr: 'تريتكسوم أستيفوم',
    country: 'Cool to temperate belts',
    iracGroup: 'N/A',
    resistanceRisk: 'Low',
    source: 'FAO • ICARDA',
    summary: 'Staple cereal crop used globally for flour, bread and animal feed.',
    summaryAr: 'محصول حبوب أساسي عالمي يُستخدم في الطحين والخبز والعلف الحيواني.',
    identification: 'Erect stems, narrow leaves and grain spikes with floral structures.',
    identificationAr: 'سيقان منتصبة، أوراق ضيقة، وسنبلة بذور ذات هيكل زهري.',
    damage: 'Yield loss from fungal diseases, drought stress and lodging.',
    damageAr: 'تسبب الأمراض الفطرية والجفاف والانحراف خسائر في الإنتاج.',
    lifeCycle: 'Usually 100–200 days depending on environment and sowing date.',
    lifeCycleAr: 'تستغرق دورة النمو عادة 100–200 يوم بحسب البيئة وتاريخ الزراعة.',
    control: 'Disease-resistant varieties, fertilization and timely irrigation.',
    controlAr: 'أصناف مقاومة للأمراض، تسميد مناسب، وری في الوقت المناسب.',
    activeIngredients: ['Nitrogen management', 'Disease control'],
    image: 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=900&q=80'
  },
  {
    id: 'rice',
    name: 'Rice',
    nameAr: 'الأرز',
    category: 'crop',
    scientificName: 'Oryza sativa',
    scientificNameAr: 'أوريا ستيتيفا',
    country: 'Wet tropical and subtropical regions',
    iracGroup: 'N/A',
    resistanceRisk: 'Low',
    source: 'IRRI • FAO',
    summary: 'Primary staple food crop grown in flooded and irrigated systems.',
    summaryAr: 'محصول غذائي أساسي يزرع في الأنظمة المروية والمغمورة.',
    identification: 'Long narrow leaves, fibrous root system and panicles on mature stems.',
    identificationAr: 'أوراق طويلة ضيقة، جذور ليفية، وسنابل في المراحل المتقدمة.',
    damage: 'Threatened by weeds, blast disease, nutrient stress and water management issues.',
    damageAr: 'يتعرض للحشائش، مرض اللفحة، الإجهاد الغذائي، ومشكلات إدارة الري.',
    lifeCycle: 'Generally 110–170 days depending on variety and water regime.',
    lifeCycleAr: 'يختلف طول دورة النمو بين 110–170 يومًا بحسب الصنف ونظام الري.',
    control: 'Water management, weed control and resistant varieties.',
    controlAr: 'إدارة المياه، مكافحة الحشائش، وأصناف مقاومة.',
    activeIngredients: ['Integrated nutrient plan', 'Water management'],
    image: 'https://images.unsplash.com/photo-1471193945509-9ad0617afabf?auto=format&fit=crop&w=900&q=80'
  },
  {
    id: 'tomato',
    name: 'Tomato',
    nameAr: 'الطماطم',
    category: 'vegetable',
    scientificName: 'Solanum lycopersicum',
    scientificNameAr: 'سولانوم ليكوبيرسكم',
    country: 'Global warm season cultivation',
    iracGroup: 'N/A',
    resistanceRisk: 'Medium',
    source: 'FAO • AVRDC',
    summary: 'High-value vegetable crop cultivated for fresh consumption and processing.',
    summaryAr: 'خضار اقتصادي مهم يُزرع للاستهلاك الطازج والتجهيز الصناعي.',
    identification: 'Shrub-like plant with compound leaves and red, yellow or pink fruit.',
    identificationAr: 'نبات شجيري بأوراق مركبة وثمار حمراء أو صفراء أو وردية.',
    damage: 'At risk from late blight, fruit borers and nutrient imbalance.',
    damageAr: 'يتعرض للمرض المتأخر، ثاقبات الثمار، وعدم توازن العناصر الغذائية.',
    lifeCycle: 'Usually 70–120 days from transplanting to first harvest.',
    lifeCycleAr: 'يصير قابلاً للحصاد عادة خلال 70–120 يومًا من الزراعة.',
    control: 'Integrated disease management, pruning, and irrigation control.',
    controlAr: 'إدارة متكاملة للأمراض، التقليم، وضبط الري.',
    activeIngredients: ['Disease protection', 'Balanced fertilization'],
    image: 'https://images.unsplash.com/photo-1546094096-0df4bcaaa337?auto=format&fit=crop&w=900&q=80'
  },
  {
    id: 'cucumber',
    name: 'Cucumber',
    nameAr: 'الخيار',
    category: 'vegetable',
    scientificName: 'Cucumis sativus',
    scientificNameAr: 'كيوكوميس ساتيفوس',
    country: 'Warm climates',
    iracGroup: 'N/A',
    resistanceRisk: 'Medium',
    source: 'FAO • AVRDC',
    summary: 'Popular cucumber vegetable grown for fresh market and pickling.',
    summaryAr: 'خضار شائع يُزرع للاستهلاك الطازج والتمليح.',
    identification: 'Vine crop with tendrils, rough leaves and elongated edible fruit.',
    identificationAr: 'نبات متسلق بأوراق خشنه ومتسلّقات وثمار مستطيلة القوام.',
    damage: 'Susceptible to powdery mildew, downy mildew and fruit rot.',
    damageAr: 'يتأثر بالبياض الدقيقي، البياض الزغبي وتعفن الثمار.',
    lifeCycle: 'Rapid growth with harvest in 45–70 days after planting.',
    lifeCycleAr: 'ينمو سريعًا ويُحصد خلال 45–70 يومًا من الزراعة.',
    control: 'Humidity control, irrigation scheduling and foliar protection.',
    controlAr: 'ضبط الرطوبة، جدول الري، وحماية ورقية مناسبة.',
    activeIngredients: ['Foliar disease control', 'Irrigation management'],
    image: 'https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?auto=format&fit=crop&w=900&q=80'
  },
  {
    id: 'onion',
    name: 'Onion',
    nameAr: 'البصل',
    category: 'vegetable',
    scientificName: 'Allium cepa',
    scientificNameAr: 'أليوم سبة',
    country: 'Temperate and subtropical zones',
    iracGroup: 'N/A',
    resistanceRisk: 'Medium',
    source: 'FAO • AVRDC',
    summary: 'Bulb vegetable valued for flavoring, storage and nutrition.',
    summaryAr: 'خضار بصلة مهم للطعم والتخزين والقيمة الغذائية.',
    identification: 'Tubular leaves and underground bulbs with layered scales.',
    identificationAr: 'أوراق أنبوبية وبصلات تحت الأرض ذات طبقات متراكبة.',
    damage: 'Affected by onion thrips, neck rot and nutrient imbalance.',
    damageAr: 'يتأثر بسوسة البصل، تعفن الرقبة وعدم توازن العناصر.',
    lifeCycle: 'Crop duration around 90–150 days depending on cultivar.',
    lifeCycleAr: 'تستغرق المحصول نحو 90–150 يومًا بحسب الصنف.',
    control: 'Soil health, irrigation and regular scouting for pests.',
    controlAr: 'صحة التربة، الري، وفحص دوري للآفات.',
    activeIngredients: ['Pest monitoring', 'Balanced fertilization'],
    image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=900&q=80'
  },
  {
    id: 'pepper',
    name: 'Pepper',
    nameAr: 'الفلفل',
    category: 'vegetable',
    scientificName: 'Capsicum annuum',
    scientificNameAr: 'كابسيسوم أنوم',
    country: 'Warm climates',
    iracGroup: 'N/A',
    resistanceRisk: 'Medium',
    source: 'AVRDC • FAO',
    summary: 'Fruit vegetable with varied colors and heat levels for fresh and processing markets.',
    summaryAr: 'خضار ثمري متنوع الألوان ودرجة الحرارة يُستعمل طازجًا ومصنّعًا.',
    identification: 'Bushy plant with fruits hanging in clusters and strong leaves.',
    identificationAr: 'نبات شجيري مع ثمار معلّقة في مجموعات وأوراق قوية.',
    damage: 'Subject to anthracnose, bacterial spot and fruit worm attacks.',
    damageAr: 'يتأثر بعفن الأنتراكنوز، البقع البكتيرية، وثاقبات الثمار.',
    lifeCycle: 'Harvest starts around 60–90 days after transplanting.',
    lifeCycleAr: 'يبدأ الحصاد بعد 60–90 يومًا من الشتل.',
    control: 'Resistance, field hygiene and pesticide rotation.',
    controlAr: 'مقاومة، نظافة الحقل، وتدوير المبيدات.',
    activeIngredients: ['Disease monitoring', 'Integrated management'],
    image: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=900&q=80'
  },
  {
    id: 'lettuce',
    name: 'Lettuce',
    nameAr: 'الخس',
    category: 'vegetable',
    scientificName: 'Lactuca sativa',
    scientificNameAr: 'لاكتوكا ساتيفا',
    country: 'Cool to temperate climates',
    iracGroup: 'N/A',
    resistanceRisk: 'Low',
    source: 'FAO • AVRDC',
    summary: 'Leafy vegetable used fresh in salads and mixed dishes.',
    summaryAr: 'خضار ورقي يُستخدم طازجًا في السلطات والأطباق المتنوعة.',
    identification: 'Rosette leaves with broad blades and short stems.',
    identificationAr: 'أوراق رُؤوسية ذات شفرات واسعة وسيقان قصيرة.',
    damage: 'Sensitive to downy mildew, aphids and bolting under heat stress.',
    damageAr: 'حساس للاصفرار الزغبي، المنّ، والتزهير تحت حرارة مرتفعة.',
    lifeCycle: 'Marketable in 30–60 days under favorable conditions.',
    lifeCycleAr: 'يصل إلى التسويق خلال 30–60 يومًا في الظروف المناسبة.',
    control: 'Shading, timely harvest and disease scouting.',
    controlAr: 'الظل الجزئي، حصاد في الوقت المناسب، ورصد الأمراض.',
    activeIngredients: ['Disease prevention', 'Irrigation balance'],
    image: 'https://images.unsplash.com/photo-1556801712-76c8eb07bbc9?auto=format&fit=crop&w=900&q=80'
  },
  {
    id: 'potato',
    name: 'Potato',
    nameAr: 'البطاطا',
    category: 'vegetable',
    scientificName: 'Solanum tuberosum',
    scientificNameAr: 'سولانوم تيوبيروسوم',
    country: 'Cool highland and temperate areas',
    iracGroup: 'N/A',
    resistanceRisk: 'Medium',
    source: 'FAO • CIP',
    summary: 'High-yield tuber crop consumed fresh and processed globally.',
    summaryAr: 'محصول درني عالي الإنتاج يُستهلك طازجًا ومصنّعًا عالميًا.',
    identification: 'Branching stems, alternate leaves and underground tubers.',
    identificationAr: 'سيقان متفرعة، أوراق متبادلة، ودرنات تحت سطح التربة.',
    damage: 'Affected by late blight, potato cyst nematodes and black scurf.',
    damageAr: 'يتأثر بالمرض المتأخر، نيماتودا درنات البطاطا، وتعفن القشرة.',
    lifeCycle: 'Matures in 80–120 days depending on cultivar and weather.',
    lifeCycleAr: 'ينضج خلال 80–120 يومًا بحسب الصنف والطقس.',
    control: 'Healthy seed, rotation and scouting for major diseases.',
    controlAr: 'بذور صحية، دورة محاصيل، ورصد للأمراض المهمة.',
    activeIngredients: ['Seed health', 'Disease rotation'],
    image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=900&q=80'
  }
];

app.get('/api/search', (req, res) => {
  const q = (req.query.q || '').toString().trim().toLowerCase();

  const filtered = !q
    ? records
    : records.filter((record) => {
        const haystack = [
          record.name,
          record.nameAr,
          record.scientificName,
          record.scientificNameAr,
          record.summary,
          record.summaryAr,
          record.country,
          record.control,
          record.controlAr,
          record.activeIngredients.join(' ')
        ].join(' ').toLowerCase();

        return haystack.includes(q);
      });

  res.json({
    count: filtered.length,
    items: filtered
  });
});

app.get('/api/records/:id', (req, res) => {
  const item = records.find((record) => record.id === req.params.id);
  if (!item) {
    return res.status(404).json({ message: 'Record not found' });
  }

  res.json({ item });
});

app.get('/api/health', (req, res) => {
  res.json({ status: 'ok', service: 'Agri Nexus API' });
});

app.listen(PORT, () => {
  console.log(`Agri Nexus API running on http://localhost:${PORT}`);
});
